[package]
name = "bunnybadger"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true, features = ["wav"] }
bevy_kira_audio = { workspace = true, features = ["wav"] }
rand = { workspace = true }
